// This file is auto generated by polygo
package models

import "gorm.io/gorm"

const authorizedDeviceTableName = "authorized_devices"

type AuthorizedDevice struct {
	gorm.Model
	RefreshToken string `gorm:"not null" json:"-"`
	UserAgent    string `json:"userAgent"`
	Ip           string `json:"ip"`
	UserID       uint   `gorm:"not null" json:"userId"`

	User *User `json:"user"`
}

type AuthorizedDeviceDTO struct {
	DTO
	RefreshToken string `gorm:"not null" json:"-"`
	UserAgent    string `json:"userAgent"`
	Ip           string `json:"ip"`
	UserID       uint   `gorm:"not null" json:"userId"`
}

type AuthorizedDevicePage struct {
	UserAgent string `json:"userAgent"`
	Ip        string `json:"ip"`
	UserID    uint   `gorm:"not null" json:"userId"`
}

func (AuthorizedDeviceDTO) TableName() string {
	return authorizedDeviceTableName
}
